// server/src/utils/permissions.js

import {
  ROLES,
  ROLE_VALUES,
} from "../config/constants.js";

const ROLE_HIERARCHY = Object.freeze({
  [ROLES.SUPER_ADMIN]: 100,
  [ROLES.ADMIN]: 90,
  [ROLES.PRINCIPAL]: 80,
  [ROLES.HR]: 70,
  [ROLES.ACCOUNTANT]: 70,
  [ROLES.COUNSELOR]: 60,
  [ROLES.TEACHER]: 60,
  [ROLES.SUPPORT]: 50,
  [ROLES.EMPLOYEE]: 40,
  [ROLES.PARENT]: 30,
  [ROLES.STUDENT]: 20,
});

const PERMISSIONS = Object.freeze({
  // Organization
  ORGANIZATION_READ: "organization:read",
  ORGANIZATION_CREATE: "organization:create",
  ORGANIZATION_UPDATE: "organization:update",
  ORGANIZATION_DELETE: "organization:delete",
  ORGANIZATION_MANAGE: "organization:manage",

  // Users
  USER_READ: "user:read",
  USER_CREATE: "user:create",
  USER_UPDATE: "user:update",
  USER_DELETE: "user:delete",
  USER_MANAGE: "user:manage",

  // Students
  STUDENT_READ: "student:read",
  STUDENT_CREATE: "student:create",
  STUDENT_UPDATE: "student:update",
  STUDENT_DELETE: "student:delete",
  STUDENT_MANAGE: "student:manage",

  // Teachers
  TEACHER_READ: "teacher:read",
  TEACHER_CREATE: "teacher:create",
  TEACHER_UPDATE: "teacher:update",
  TEACHER_DELETE: "teacher:delete",
  TEACHER_MANAGE: "teacher:manage",

  // Employees
  EMPLOYEE_READ: "employee:read",
  EMPLOYEE_CREATE: "employee:create",
  EMPLOYEE_UPDATE: "employee:update",
  EMPLOYEE_DELETE: "employee:delete",
  EMPLOYEE_MANAGE: "employee:manage",

  // Parents
  PARENT_READ: "parent:read",
  PARENT_CREATE: "parent:create",
  PARENT_UPDATE: "parent:update",
  PARENT_DELETE: "parent:delete",
  PARENT_MANAGE: "parent:manage",

  // Departments
  DEPARTMENT_READ: "department:read",
  DEPARTMENT_CREATE: "department:create",
  DEPARTMENT_UPDATE: "department:update",
  DEPARTMENT_DELETE: "department:delete",
  DEPARTMENT_MANAGE: "department:manage",

  // Classes
  CLASS_READ: "class:read",
  CLASS_CREATE: "class:create",
  CLASS_UPDATE: "class:update",
  CLASS_DELETE: "class:delete",
  CLASS_MANAGE: "class:manage",

  // Enrollment
  ENROLLMENT_READ: "enrollment:read",
  ENROLLMENT_CREATE: "enrollment:create",
  ENROLLMENT_UPDATE: "enrollment:update",
  ENROLLMENT_DELETE: "enrollment:delete",
  ENROLLMENT_MANAGE: "enrollment:manage",

  // Attendance
  ATTENDANCE_READ: "attendance:read",
  ATTENDANCE_CREATE: "attendance:create",
  ATTENDANCE_UPDATE: "attendance:update",
  ATTENDANCE_DELETE: "attendance:delete",
  ATTENDANCE_MANAGE: "attendance:manage",

  // Geofence / QR / Devices
  GEOFENCE_READ: "geofence:read",
  GEOFENCE_CREATE: "geofence:create",
  GEOFENCE_UPDATE: "geofence:update",
  GEOFENCE_DELETE: "geofence:delete",
  GEOFENCE_MANAGE: "geofence:manage",

  QR_SESSION_READ: "qr_session:read",
  QR_SESSION_CREATE: "qr_session:create",
  QR_SESSION_UPDATE: "qr_session:update",
  QR_SESSION_DELETE: "qr_session:delete",
  QR_SESSION_MANAGE: "qr_session:manage",

  DEVICE_READ: "device:read",
  DEVICE_CREATE: "device:create",
  DEVICE_UPDATE: "device:update",
  DEVICE_DELETE: "device:delete",
  DEVICE_MANAGE: "device:manage",

  // Assignments
  ASSIGNMENT_READ: "assignment:read",
  ASSIGNMENT_CREATE: "assignment:create",
  ASSIGNMENT_UPDATE: "assignment:update",
  ASSIGNMENT_DELETE: "assignment:delete",
  ASSIGNMENT_MANAGE: "assignment:manage",

  // Submissions
  SUBMISSION_READ: "submission:read",
  SUBMISSION_CREATE: "submission:create",
  SUBMISSION_UPDATE: "submission:update",
  SUBMISSION_DELETE: "submission:delete",
  SUBMISSION_MANAGE: "submission:manage",

  // Tests
  TEST_READ: "test:read",
  TEST_CREATE: "test:create",
  TEST_UPDATE: "test:update",
  TEST_DELETE: "test:delete",
  TEST_MANAGE: "test:manage",

  // Questions
  QUESTION_READ: "question:read",
  QUESTION_CREATE: "question:create",
  QUESTION_UPDATE: "question:update",
  QUESTION_DELETE: "question:delete",
  QUESTION_MANAGE: "question:manage",

  // Test Attempts
  TEST_ATTEMPT_READ: "test_attempt:read",
  TEST_ATTEMPT_CREATE: "test_attempt:create",
  TEST_ATTEMPT_UPDATE: "test_attempt:update",
  TEST_ATTEMPT_MANAGE: "test_attempt:manage",

  // Live Sessions
  LIVE_SESSION_READ: "live_session:read",
  LIVE_SESSION_CREATE: "live_session:create",
  LIVE_SESSION_UPDATE: "live_session:update",
  LIVE_SESSION_DELETE: "live_session:delete",
  LIVE_SESSION_MANAGE: "live_session:manage",

  // Study Material
  STUDY_MATERIAL_READ: "study_material:read",
  STUDY_MATERIAL_CREATE: "study_material:create",
  STUDY_MATERIAL_UPDATE: "study_material:update",
  STUDY_MATERIAL_DELETE: "study_material:delete",
  STUDY_MATERIAL_MANAGE: "study_material:manage",

  // Notifications
  NOTIFICATION_READ: "notification:read",
  NOTIFICATION_CREATE: "notification:create",
  NOTIFICATION_UPDATE: "notification:update",
  NOTIFICATION_DELETE: "notification:delete",
  NOTIFICATION_MANAGE: "notification:manage",

  // Notification preferences
  NOTIFICATION_PREFERENCE_READ:
    "notification_preference:read",
  NOTIFICATION_PREFERENCE_UPDATE:
    "notification_preference:update",
  NOTIFICATION_PREFERENCE_MANAGE:
    "notification_preference:manage",

  // CRM
  CRM_READ: "crm:read",
  CRM_CREATE: "crm:create",
  CRM_UPDATE: "crm:update",
  CRM_DELETE: "crm:delete",
  CRM_MANAGE: "crm:manage",

  LEAD_READ: "lead:read",
  LEAD_CREATE: "lead:create",
  LEAD_UPDATE: "lead:update",
  LEAD_DELETE: "lead:delete",
  LEAD_MANAGE: "lead:manage",

  CONTACT_READ: "contact:read",
  CONTACT_CREATE: "contact:create",
  CONTACT_UPDATE: "contact:update",
  CONTACT_DELETE: "contact:delete",
  CONTACT_MANAGE: "contact:manage",

  DEAL_READ: "deal:read",
  DEAL_CREATE: "deal:create",
  DEAL_UPDATE: "deal:update",
  DEAL_DELETE: "deal:delete",
  DEAL_MANAGE: "deal:manage",

  PIPELINE_READ: "pipeline:read",
  PIPELINE_CREATE: "pipeline:create",
  PIPELINE_UPDATE: "pipeline:update",
  PIPELINE_DELETE: "pipeline:delete",
  PIPELINE_MANAGE: "pipeline:manage",

  CRM_ACTIVITY_READ: "crm_activity:read",
  CRM_ACTIVITY_CREATE: "crm_activity:create",
  CRM_ACTIVITY_UPDATE: "crm_activity:update",
  CRM_ACTIVITY_DELETE: "crm_activity:delete",
  CRM_ACTIVITY_MANAGE: "crm_activity:manage",

  CRM_TASK_READ: "crm_task:read",
  CRM_TASK_CREATE: "crm_task:create",
  CRM_TASK_UPDATE: "crm_task:update",
  CRM_TASK_DELETE: "crm_task:delete",
  CRM_TASK_MANAGE: "crm_task:manage",

  CRM_NOTE_READ: "crm_note:read",
  CRM_NOTE_CREATE: "crm_note:create",
  CRM_NOTE_UPDATE: "crm_note:update",
  CRM_NOTE_DELETE: "crm_note:delete",
  CRM_NOTE_MANAGE: "crm_note:manage",

  CUSTOMER_READ: "customer:read",
  CUSTOMER_CREATE: "customer:create",
  CUSTOMER_UPDATE: "customer:update",
  CUSTOMER_DELETE: "customer:delete",
  CUSTOMER_MANAGE: "customer:manage",

  // Communication
  CONVERSATION_READ: "conversation:read",
  CONVERSATION_CREATE: "conversation:create",
  CONVERSATION_UPDATE: "conversation:update",
  CONVERSATION_DELETE: "conversation:delete",
  CONVERSATION_MANAGE: "conversation:manage",

  MESSAGE_READ: "message:read",
  MESSAGE_CREATE: "message:create",
  MESSAGE_UPDATE: "message:update",
  MESSAGE_DELETE: "message:delete",
  MESSAGE_MANAGE: "message:manage",

  // Support
  SUPPORT_READ: "support:read",
  SUPPORT_CREATE: "support:create",
  SUPPORT_UPDATE: "support:update",
  SUPPORT_DELETE: "support:delete",
  SUPPORT_MANAGE: "support:manage",

  TICKET_READ: "ticket:read",
  TICKET_CREATE: "ticket:create",
  TICKET_UPDATE: "ticket:update",
  TICKET_DELETE: "ticket:delete",
  TICKET_MANAGE: "ticket:manage",

  TICKET_MESSAGE_READ: "ticket_message:read",
  TICKET_MESSAGE_CREATE: "ticket_message:create",
  TICKET_MESSAGE_UPDATE: "ticket_message:update",
  TICKET_MESSAGE_DELETE: "ticket_message:delete",
  TICKET_MESSAGE_MANAGE: "ticket_message:manage",

  // Gamification
  GAMIFICATION_READ: "gamification:read",
  GAMIFICATION_CREATE: "gamification:create",
  GAMIFICATION_UPDATE: "gamification:update",
  GAMIFICATION_DELETE: "gamification:delete",
  GAMIFICATION_MANAGE: "gamification:manage",

  ACHIEVEMENT_READ: "achievement:read",
  ACHIEVEMENT_CREATE: "achievement:create",
  ACHIEVEMENT_UPDATE: "achievement:update",
  ACHIEVEMENT_DELETE: "achievement:delete",
  ACHIEVEMENT_MANAGE: "achievement:manage",

  POINT_LEDGER_READ: "point_ledger:read",
  POINT_LEDGER_CREATE: "point_ledger:create",
  POINT_LEDGER_MANAGE: "point_ledger:manage",

  USER_ACHIEVEMENT_READ: "user_achievement:read",
  USER_ACHIEVEMENT_CREATE: "user_achievement:create",
  USER_ACHIEVEMENT_UPDATE: "user_achievement:update",
  USER_ACHIEVEMENT_MANAGE: "user_achievement:manage",

  LEADERBOARD_READ: "leaderboard:read",
  LEADERBOARD_MANAGE: "leaderboard:manage",

  STREAK_READ: "streak:read",
  STREAK_CREATE: "streak:create",
  STREAK_UPDATE: "streak:update",
  STREAK_MANAGE: "streak:manage",

  // HR
  HR_READ: "hr:read",
  HR_CREATE: "hr:create",
  HR_UPDATE: "hr:update",
  HR_DELETE: "hr:delete",
  HR_MANAGE: "hr:manage",

  LEAVE_READ: "leave:read",
  LEAVE_CREATE: "leave:create",
  LEAVE_UPDATE: "leave:update",
  LEAVE_DELETE: "leave:delete",
  LEAVE_APPROVE: "leave:approve",
  LEAVE_MANAGE: "leave:manage",

  PERFORMANCE_READ: "performance:read",
  PERFORMANCE_CREATE: "performance:create",
  PERFORMANCE_UPDATE: "performance:update",
  PERFORMANCE_DELETE: "performance:delete",
  PERFORMANCE_MANAGE: "performance:manage",

  EMPLOYEE_DOCUMENT_READ:
    "employee_document:read",
  EMPLOYEE_DOCUMENT_CREATE:
    "employee_document:create",
  EMPLOYEE_DOCUMENT_UPDATE:
    "employee_document:update",
  EMPLOYEE_DOCUMENT_DELETE:
    "employee_document:delete",
  EMPLOYEE_DOCUMENT_MANAGE:
    "employee_document:manage",

  SALARY_STRUCTURE_READ:
    "salary_structure:read",
  SALARY_STRUCTURE_CREATE:
    "salary_structure:create",
  SALARY_STRUCTURE_UPDATE:
    "salary_structure:update",
  SALARY_STRUCTURE_DELETE:
    "salary_structure:delete",
  SALARY_STRUCTURE_MANAGE:
    "salary_structure:manage",

  PAYROLL_READ: "payroll:read",
  PAYROLL_CREATE: "payroll:create",
  PAYROLL_UPDATE: "payroll:update",
  PAYROLL_DELETE: "payroll:delete",
  PAYROLL_MANAGE: "payroll:manage",

  // Finance
  FINANCE_READ: "finance:read",
  FINANCE_CREATE: "finance:create",
  FINANCE_UPDATE: "finance:update",
  FINANCE_DELETE: "finance:delete",
  FINANCE_MANAGE: "finance:manage",

  INVOICE_READ: "invoice:read",
  INVOICE_CREATE: "invoice:create",
  INVOICE_UPDATE: "invoice:update",
  INVOICE_DELETE: "invoice:delete",
  INVOICE_MANAGE: "invoice:manage",

  PAYMENT_READ: "payment:read",
  PAYMENT_CREATE: "payment:create",
  PAYMENT_UPDATE: "payment:update",
  PAYMENT_REFUND: "payment:refund",
  PAYMENT_MANAGE: "payment:manage",

  // Certificates
  CERTIFICATE_READ: "certificate:read",
  CERTIFICATE_CREATE: "certificate:create",
  CERTIFICATE_UPDATE: "certificate:update",
  CERTIFICATE_DELETE: "certificate:delete",
  CERTIFICATE_REVOKE: "certificate:revoke",
  CERTIFICATE_MANAGE: "certificate:manage",

  // Audit / Reports
  AUDIT_READ: "audit:read",
  AUDIT_EXPORT: "audit:export",

  REPORT_READ: "report:read",
  REPORT_EXPORT: "report:export",

  // Settings
  SETTINGS_READ: "settings:read",
  SETTINGS_UPDATE: "settings:update",
  SETTINGS_MANAGE: "settings:manage",
});

const ALL_PERMISSIONS = Object.freeze(
  Object.values(PERMISSIONS)
);

const rolePermissions = Object.freeze({
  [ROLES.SUPER_ADMIN]: ALL_PERMISSIONS,

  [ROLES.ADMIN]: [
    PERMISSIONS.ORGANIZATION_READ,
    PERMISSIONS.ORGANIZATION_UPDATE,
    PERMISSIONS.ORGANIZATION_MANAGE,

    PERMISSIONS.USER_READ,
    PERMISSIONS.USER_CREATE,
    PERMISSIONS.USER_UPDATE,
    PERMISSIONS.USER_DELETE,
    PERMISSIONS.USER_MANAGE,

    PERMISSIONS.STUDENT_READ,
    PERMISSIONS.STUDENT_CREATE,
    PERMISSIONS.STUDENT_UPDATE,
    PERMISSIONS.STUDENT_DELETE,
    PERMISSIONS.STUDENT_MANAGE,

    PERMISSIONS.TEACHER_READ,
    PERMISSIONS.TEACHER_CREATE,
    PERMISSIONS.TEACHER_UPDATE,
    PERMISSIONS.TEACHER_DELETE,
    PERMISSIONS.TEACHER_MANAGE,

    PERMISSIONS.EMPLOYEE_READ,
    PERMISSIONS.EMPLOYEE_CREATE,
    PERMISSIONS.EMPLOYEE_UPDATE,
    PERMISSIONS.EMPLOYEE_DELETE,
    PERMISSIONS.EMPLOYEE_MANAGE,

    PERMISSIONS.PARENT_READ,
    PERMISSIONS.PARENT_CREATE,
    PERMISSIONS.PARENT_UPDATE,
    PERMISSIONS.PARENT_DELETE,
    PERMISSIONS.PARENT_MANAGE,

    PERMISSIONS.DEPARTMENT_READ,
    PERMISSIONS.DEPARTMENT_CREATE,
    PERMISSIONS.DEPARTMENT_UPDATE,
    PERMISSIONS.DEPARTMENT_DELETE,
    PERMISSIONS.DEPARTMENT_MANAGE,

    PERMISSIONS.CLASS_READ,
    PERMISSIONS.CLASS_CREATE,
    PERMISSIONS.CLASS_UPDATE,
    PERMISSIONS.CLASS_DELETE,
    PERMISSIONS.CLASS_MANAGE,

    PERMISSIONS.ENROLLMENT_READ,
    PERMISSIONS.ENROLLMENT_CREATE,
    PERMISSIONS.ENROLLMENT_UPDATE,
    PERMISSIONS.ENROLLMENT_DELETE,
    PERMISSIONS.ENROLLMENT_MANAGE,

    PERMISSIONS.ATTENDANCE_READ,
    PERMISSIONS.ATTENDANCE_CREATE,
    PERMISSIONS.ATTENDANCE_UPDATE,
    PERMISSIONS.ATTENDANCE_DELETE,
    PERMISSIONS.ATTENDANCE_MANAGE,

    PERMISSIONS.GEOFENCE_READ,
    PERMISSIONS.GEOFENCE_CREATE,
    PERMISSIONS.GEOFENCE_UPDATE,
    PERMISSIONS.GEOFENCE_DELETE,
    PERMISSIONS.GEOFENCE_MANAGE,

    PERMISSIONS.QR_SESSION_READ,
    PERMISSIONS.QR_SESSION_CREATE,
    PERMISSIONS.QR_SESSION_UPDATE,
    PERMISSIONS.QR_SESSION_DELETE,
    PERMISSIONS.QR_SESSION_MANAGE,

    PERMISSIONS.DEVICE_READ,
    PERMISSIONS.DEVICE_MANAGE,

    PERMISSIONS.ASSIGNMENT_READ,
    PERMISSIONS.ASSIGNMENT_CREATE,
    PERMISSIONS.ASSIGNMENT_UPDATE,
    PERMISSIONS.ASSIGNMENT_DELETE,
    PERMISSIONS.ASSIGNMENT_MANAGE,

    PERMISSIONS.SUBMISSION_READ,
    PERMISSIONS.SUBMISSION_CREATE,
    PERMISSIONS.SUBMISSION_UPDATE,
    PERMISSIONS.SUBMISSION_DELETE,
    PERMISSIONS.SUBMISSION_MANAGE,

    PERMISSIONS.TEST_READ,
    PERMISSIONS.TEST_CREATE,
    PERMISSIONS.TEST_UPDATE,
    PERMISSIONS.TEST_DELETE,
    PERMISSIONS.TEST_MANAGE,

    PERMISSIONS.QUESTION_READ,
    PERMISSIONS.QUESTION_CREATE,
    PERMISSIONS.QUESTION_UPDATE,
    PERMISSIONS.QUESTION_DELETE,
    PERMISSIONS.QUESTION_MANAGE,

    PERMISSIONS.TEST_ATTEMPT_READ,
    PERMISSIONS.TEST_ATTEMPT_CREATE,
    PERMISSIONS.TEST_ATTEMPT_UPDATE,
    PERMISSIONS.TEST_ATTEMPT_MANAGE,

    PERMISSIONS.LIVE_SESSION_READ,
    PERMISSIONS.LIVE_SESSION_CREATE,
    PERMISSIONS.LIVE_SESSION_UPDATE,
    PERMISSIONS.LIVE_SESSION_DELETE,
    PERMISSIONS.LIVE_SESSION_MANAGE,

    PERMISSIONS.STUDY_MATERIAL_READ,
    PERMISSIONS.STUDY_MATERIAL_CREATE,
    PERMISSIONS.STUDY_MATERIAL_UPDATE,
    PERMISSIONS.STUDY_MATERIAL_DELETE,
    PERMISSIONS.STUDY_MATERIAL_MANAGE,

    PERMISSIONS.NOTIFICATION_READ,
    PERMISSIONS.NOTIFICATION_CREATE,
    PERMISSIONS.NOTIFICATION_UPDATE,
    PERMISSIONS.NOTIFICATION_DELETE,
    PERMISSIONS.NOTIFICATION_MANAGE,

    PERMISSIONS.CRM_READ,
    PERMISSIONS.CRM_CREATE,
    PERMISSIONS.CRM_UPDATE,
    PERMISSIONS.CRM_DELETE,
    PERMISSIONS.CRM_MANAGE,

    PERMISSIONS.LEAD_READ,
    PERMISSIONS.LEAD_CREATE,
    PERMISSIONS.LEAD_UPDATE,
    PERMISSIONS.LEAD_DELETE,
    PERMISSIONS.LEAD_MANAGE,

    PERMISSIONS.CONTACT_READ,
    PERMISSIONS.CONTACT_CREATE,
    PERMISSIONS.CONTACT_UPDATE,
    PERMISSIONS.CONTACT_DELETE,
    PERMISSIONS.CONTACT_MANAGE,

    PERMISSIONS.DEAL_READ,
    PERMISSIONS.DEAL_CREATE,
    PERMISSIONS.DEAL_UPDATE,
    PERMISSIONS.DEAL_DELETE,
    PERMISSIONS.DEAL_MANAGE,

    PERMISSIONS.PIPELINE_READ,
    PERMISSIONS.PIPELINE_CREATE,
    PERMISSIONS.PIPELINE_UPDATE,
    PERMISSIONS.PIPELINE_DELETE,
    PERMISSIONS.PIPELINE_MANAGE,

    PERMISSIONS.CRM_ACTIVITY_READ,
    PERMISSIONS.CRM_ACTIVITY_CREATE,
    PERMISSIONS.CRM_ACTIVITY_UPDATE,
    PERMISSIONS.CRM_ACTIVITY_DELETE,
    PERMISSIONS.CRM_ACTIVITY_MANAGE,

    PERMISSIONS.CRM_TASK_READ,
    PERMISSIONS.CRM_TASK_CREATE,
    PERMISSIONS.CRM_TASK_UPDATE,
    PERMISSIONS.CRM_TASK_DELETE,
    PERMISSIONS.CRM_TASK_MANAGE,

    PERMISSIONS.CRM_NOTE_READ,
    PERMISSIONS.CRM_NOTE_CREATE,
    PERMISSIONS.CRM_NOTE_UPDATE,
    PERMISSIONS.CRM_NOTE_DELETE,
    PERMISSIONS.CRM_NOTE_MANAGE,

    PERMISSIONS.CUSTOMER_READ,
    PERMISSIONS.CUSTOMER_CREATE,
    PERMISSIONS.CUSTOMER_UPDATE,
    PERMISSIONS.CUSTOMER_DELETE,
    PERMISSIONS.CUSTOMER_MANAGE,

    PERMISSIONS.CONVERSATION_READ,
    PERMISSIONS.CONVERSATION_CREATE,
    PERMISSIONS.CONVERSATION_UPDATE,
    PERMISSIONS.CONVERSATION_DELETE,
    PERMISSIONS.CONVERSATION_MANAGE,

    PERMISSIONS.MESSAGE_READ,
    PERMISSIONS.MESSAGE_CREATE,
    PERMISSIONS.MESSAGE_UPDATE,
    PERMISSIONS.MESSAGE_DELETE,
    PERMISSIONS.MESSAGE_MANAGE,

    PERMISSIONS.SUPPORT_READ,
    PERMISSIONS.SUPPORT_CREATE,
    PERMISSIONS.SUPPORT_UPDATE,
    PERMISSIONS.SUPPORT_DELETE,
    PERMISSIONS.SUPPORT_MANAGE,

    PERMISSIONS.TICKET_READ,
    PERMISSIONS.TICKET_CREATE,
    PERMISSIONS.TICKET_UPDATE,
    PERMISSIONS.TICKET_DELETE,
    PERMISSIONS.TICKET_MANAGE,

    PERMISSIONS.TICKET_MESSAGE_READ,
    PERMISSIONS.TICKET_MESSAGE_CREATE,
    PERMISSIONS.TICKET_MESSAGE_UPDATE,
    PERMISSIONS.TICKET_MESSAGE_DELETE,
    PERMISSIONS.TICKET_MESSAGE_MANAGE,

    PERMISSIONS.GAMIFICATION_READ,
    PERMISSIONS.GAMIFICATION_CREATE,
    PERMISSIONS.GAMIFICATION_UPDATE,
    PERMISSIONS.GAMIFICATION_DELETE,
    PERMISSIONS.GAMIFICATION_MANAGE,

    PERMISSIONS.ACHIEVEMENT_READ,
    PERMISSIONS.ACHIEVEMENT_CREATE,
    PERMISSIONS.ACHIEVEMENT_UPDATE,
    PERMISSIONS.ACHIEVEMENT_DELETE,
    PERMISSIONS.ACHIEVEMENT_MANAGE,

    PERMISSIONS.POINT_LEDGER_READ,
    PERMISSIONS.POINT_LEDGER_CREATE,
    PERMISSIONS.POINT_LEDGER_MANAGE,

    PERMISSIONS.USER_ACHIEVEMENT_READ,
    PERMISSIONS.USER_ACHIEVEMENT_CREATE,
    PERMISSIONS.USER_ACHIEVEMENT_UPDATE,
    PERMISSIONS.USER_ACHIEVEMENT_MANAGE,

    PERMISSIONS.LEADERBOARD_READ,
    PERMISSIONS.LEADERBOARD_MANAGE,

    PERMISSIONS.STREAK_READ,
    PERMISSIONS.STREAK_CREATE,
    PERMISSIONS.STREAK_UPDATE,
    PERMISSIONS.STREAK_MANAGE,

    PERMISSIONS.HR_READ,
    PERMISSIONS.HR_CREATE,
    PERMISSIONS.HR_UPDATE,
    PERMISSIONS.HR_DELETE,
    PERMISSIONS.HR_MANAGE,

    PERMISSIONS.LEAVE_READ,
    PERMISSIONS.LEAVE_CREATE,
    PERMISSIONS.LEAVE_UPDATE,
    PERMISSIONS.LEAVE_DELETE,
    PERMISSIONS.LEAVE_APPROVE,
    PERMISSIONS.LEAVE_MANAGE,

    PERMISSIONS.PERFORMANCE_READ,
    PERMISSIONS.PERFORMANCE_CREATE,
    PERMISSIONS.PERFORMANCE_UPDATE,
    PERMISSIONS.PERFORMANCE_DELETE,
    PERMISSIONS.PERFORMANCE_MANAGE,

    PERMISSIONS.EMPLOYEE_DOCUMENT_READ,
    PERMISSIONS.EMPLOYEE_DOCUMENT_CREATE,
    PERMISSIONS.EMPLOYEE_DOCUMENT_UPDATE,
    PERMISSIONS.EMPLOYEE_DOCUMENT_DELETE,
    PERMISSIONS.EMPLOYEE_DOCUMENT_MANAGE,

    PERMISSIONS.SALARY_STRUCTURE_READ,
    PERMISSIONS.SALARY_STRUCTURE_CREATE,
    PERMISSIONS.SALARY_STRUCTURE_UPDATE,
    PERMISSIONS.SALARY_STRUCTURE_DELETE,
    PERMISSIONS.SALARY_STRUCTURE_MANAGE,

    PERMISSIONS.PAYROLL_READ,
    PERMISSIONS.PAYROLL_CREATE,
    PERMISSIONS.PAYROLL_UPDATE,
    PERMISSIONS.PAYROLL_DELETE,
    PERMISSIONS.PAYROLL_MANAGE,

    PERMISSIONS.FINANCE_READ,
    PERMISSIONS.FINANCE_CREATE,
    PERMISSIONS.FINANCE_UPDATE,
    PERMISSIONS.FINANCE_DELETE,
    PERMISSIONS.FINANCE_MANAGE,

    PERMISSIONS.INVOICE_READ,
    PERMISSIONS.INVOICE_CREATE,
    PERMISSIONS.INVOICE_UPDATE,
    PERMISSIONS.INVOICE_DELETE,
    PERMISSIONS.INVOICE_MANAGE,

    PERMISSIONS.PAYMENT_READ,
    PERMISSIONS.PAYMENT_CREATE,
    PERMISSIONS.PAYMENT_UPDATE,
    PERMISSIONS.PAYMENT_REFUND,
    PERMISSIONS.PAYMENT_MANAGE,

    PERMISSIONS.CERTIFICATE_READ,
    PERMISSIONS.CERTIFICATE_CREATE,
    PERMISSIONS.CERTIFICATE_UPDATE,
    PERMISSIONS.CERTIFICATE_DELETE,
    PERMISSIONS.CERTIFICATE_REVOKE,
    PERMISSIONS.CERTIFICATE_MANAGE,

    PERMISSIONS.AUDIT_READ,
    PERMISSIONS.AUDIT_EXPORT,

    PERMISSIONS.REPORT_READ,
    PERMISSIONS.REPORT_EXPORT,

    PERMISSIONS.SETTINGS_READ,
    PERMISSIONS.SETTINGS_UPDATE,
    PERMISSIONS.SETTINGS_MANAGE,
  ],

  [ROLES.PRINCIPAL]: [
    PERMISSIONS.USER_READ,
    PERMISSIONS.USER_UPDATE,

    PERMISSIONS.STUDENT_READ,
    PERMISSIONS.STUDENT_CREATE,
    PERMISSIONS.STUDENT_UPDATE,

    PERMISSIONS.TEACHER_READ,
    PERMISSIONS.TEACHER_CREATE,
    PERMISSIONS.TEACHER_UPDATE,

    PERMISSIONS.EMPLOYEE_READ,

    PERMISSIONS.PARENT_READ,
    PERMISSIONS.PARENT_UPDATE,

    PERMISSIONS.DEPARTMENT_READ,
    PERMISSIONS.DEPARTMENT_UPDATE,

    PERMISSIONS.CLASS_READ,
    PERMISSIONS.CLASS_CREATE,
    PERMISSIONS.CLASS_UPDATE,
    PERMISSIONS.CLASS_MANAGE,

    PERMISSIONS.ENROLLMENT_READ,
    PERMISSIONS.ENROLLMENT_CREATE,
    PERMISSIONS.ENROLLMENT_UPDATE,

    PERMISSIONS.ATTENDANCE_READ,
    PERMISSIONS.ATTENDANCE_CREATE,
    PERMISSIONS.ATTENDANCE_UPDATE,
    PERMISSIONS.ATTENDANCE_MANAGE,

    PERMISSIONS.ASSIGNMENT_READ,
    PERMISSIONS.ASSIGNMENT_CREATE,
    PERMISSIONS.ASSIGNMENT_UPDATE,
    PERMISSIONS.ASSIGNMENT_MANAGE,

    PERMISSIONS.SUBMISSION_READ,
    PERMISSIONS.SUBMISSION_UPDATE,
    PERMISSIONS.SUBMISSION_MANAGE,

    PERMISSIONS.TEST_READ,
    PERMISSIONS.TEST_CREATE,
    PERMISSIONS.TEST_UPDATE,
    PERMISSIONS.TEST_MANAGE,

    PERMISSIONS.QUESTION_READ,
    PERMISSIONS.QUESTION_CREATE,
    PERMISSIONS.QUESTION_UPDATE,

    PERMISSIONS.LIVE_SESSION_READ,
    PERMISSIONS.LIVE_SESSION_CREATE,
    PERMISSIONS.LIVE_SESSION_UPDATE,

    PERMISSIONS.STUDY_MATERIAL_READ,
    PERMISSIONS.STUDY_MATERIAL_CREATE,
    PERMISSIONS.STUDY_MATERIAL_UPDATE,

    PERMISSIONS.NOTIFICATION_READ,
    PERMISSIONS.NOTIFICATION_CREATE,

    PERMISSIONS.ACHIEVEMENT_READ,
    PERMISSIONS.ACHIEVEMENT_CREATE,
    PERMISSIONS.USER_ACHIEVEMENT_READ,
    PERMISSIONS.LEADERBOARD_READ,
    PERMISSIONS.STREAK_READ,

    PERMISSIONS.PERFORMANCE_READ,
    PERMISSIONS.PERFORMANCE_CREATE,
    PERMISSIONS.PERFORMANCE_UPDATE,

    PERMISSIONS.CERTIFICATE_READ,
    PERMISSIONS.CERTIFICATE_CREATE,

    PERMISSIONS.REPORT_READ,
    PERMISSIONS.REPORT_EXPORT,
  ],

  [ROLES.HR]: [
    PERMISSIONS.USER_READ,
    PERMISSIONS.USER_UPDATE,

    PERMISSIONS.EMPLOYEE_READ,
    PERMISSIONS.EMPLOYEE_CREATE,
    PERMISSIONS.EMPLOYEE_UPDATE,
    PERMISSIONS.EMPLOYEE_MANAGE,

    PERMISSIONS.DEPARTMENT_READ,
    PERMISSIONS.DEPARTMENT_UPDATE,

    PERMISSIONS.ATTENDANCE_READ,
    PERMISSIONS.ATTENDANCE_UPDATE,

    PERMISSIONS.LEAVE_READ,
    PERMISSIONS.LEAVE_CREATE,
    PERMISSIONS.LEAVE_UPDATE,
    PERMISSIONS.LEAVE_DELETE,
    PERMISSIONS.LEAVE_APPROVE,
    PERMISSIONS.LEAVE_MANAGE,

    PERMISSIONS.HR_READ,
    PERMISSIONS.HR_CREATE,
    PERMISSIONS.HR_UPDATE,
    PERMISSIONS.HR_MANAGE,

    PERMISSIONS.PERFORMANCE_READ,
    PERMISSIONS.PERFORMANCE_CREATE,
    PERMISSIONS.PERFORMANCE_UPDATE,
    PERMISSIONS.PERFORMANCE_MANAGE,

    PERMISSIONS.EMPLOYEE_DOCUMENT_READ,
    PERMISSIONS.EMPLOYEE_DOCUMENT_CREATE,
    PERMISSIONS.EMPLOYEE_DOCUMENT_UPDATE,
    PERMISSIONS.EMPLOYEE_DOCUMENT_DELETE,
    PERMISSIONS.EMPLOYEE_DOCUMENT_MANAGE,

    PERMISSIONS.SALARY_STRUCTURE_READ,
    PERMISSIONS.SALARY_STRUCTURE_CREATE,
    PERMISSIONS.SALARY_STRUCTURE_UPDATE,
    PERMISSIONS.SALARY_STRUCTURE_MANAGE,

    PERMISSIONS.PAYROLL_READ,
    PERMISSIONS.PAYROLL_CREATE,
    PERMISSIONS.PAYROLL_UPDATE,

    PERMISSIONS.NOTIFICATION_READ,
    PERMISSIONS.NOTIFICATION_CREATE,

    PERMISSIONS.REPORT_READ,
    PERMISSIONS.REPORT_EXPORT,

    PERMISSIONS.DEVICE_READ,
  ],

  [ROLES.ACCOUNTANT]: [
    PERMISSIONS.USER_READ,

    PERMISSIONS.STUDENT_READ,
    PERMISSIONS.EMPLOYEE_READ,

    PERMISSIONS.ENROLLMENT_READ,

    PERMISSIONS.FINANCE_READ,
    PERMISSIONS.FINANCE_CREATE,
    PERMISSIONS.FINANCE_UPDATE,
    PERMISSIONS.FINANCE_MANAGE,

    PERMISSIONS.INVOICE_READ,
    PERMISSIONS.INVOICE_CREATE,
    PERMISSIONS.INVOICE_UPDATE,
    PERMISSIONS.INVOICE_MANAGE,

    PERMISSIONS.PAYMENT_READ,
    PERMISSIONS.PAYMENT_CREATE,
    PERMISSIONS.PAYMENT_UPDATE,
    PERMISSIONS.PAYMENT_REFUND,
    PERMISSIONS.PAYMENT_MANAGE,

    PERMISSIONS.PAYROLL_READ,

    PERMISSIONS.SALARY_STRUCTURE_READ,

    PERMISSIONS.REPORT_READ,
    PERMISSIONS.REPORT_EXPORT,

    PERMISSIONS.NOTIFICATION_READ,
  ],

  [ROLES.COUNSELOR]: [
    PERMISSIONS.USER_READ,

    PERMISSIONS.STUDENT_READ,
    PERMISSIONS.STUDENT_CREATE,
    PERMISSIONS.STUDENT_UPDATE,

    PERMISSIONS.PARENT_READ,
    PERMISSIONS.PARENT_CREATE,
    PERMISSIONS.PARENT_UPDATE,

    PERMISSIONS.ENROLLMENT_READ,
    PERMISSIONS.ENROLLMENT_CREATE,
    PERMISSIONS.ENROLLMENT_UPDATE,

    PERMISSIONS.CRM_READ,
    PERMISSIONS.CRM_CREATE,
    PERMISSIONS.CRM_UPDATE,

    PERMISSIONS.LEAD_READ,
    PERMISSIONS.LEAD_CREATE,
    PERMISSIONS.LEAD_UPDATE,

    PERMISSIONS.CONTACT_READ,
    PERMISSIONS.CONTACT_CREATE,
    PERMISSIONS.CONTACT_UPDATE,

    PERMISSIONS.DEAL_READ,
    PERMISSIONS.DEAL_CREATE,
    PERMISSIONS.DEAL_UPDATE,

    PERMISSIONS.PIPELINE_READ,

    PERMISSIONS.CRM_ACTIVITY_READ,
    PERMISSIONS.CRM_ACTIVITY_CREATE,
    PERMISSIONS.CRM_ACTIVITY_UPDATE,

    PERMISSIONS.CRM_TASK_READ,
    PERMISSIONS.CRM_TASK_CREATE,
    PERMISSIONS.CRM_TASK_UPDATE,

    PERMISSIONS.CRM_NOTE_READ,
    PERMISSIONS.CRM_NOTE_CREATE,
    PERMISSIONS.CRM_NOTE_UPDATE,

    PERMISSIONS.CUSTOMER_READ,
    PERMISSIONS.CUSTOMER_CREATE,
    PERMISSIONS.CUSTOMER_UPDATE,

    PERMISSIONS.CONVERSATION_READ,
    PERMISSIONS.CONVERSATION_CREATE,
    PERMISSIONS.CONVERSATION_UPDATE,

    PERMISSIONS.MESSAGE_READ,
    PERMISSIONS.MESSAGE_CREATE,
    PERMISSIONS.MESSAGE_UPDATE,

    PERMISSIONS.NOTIFICATION_READ,
    PERMISSIONS.NOTIFICATION_CREATE,

    PERMISSIONS.REPORT_READ,
  ],

  [ROLES.TEACHER]: [
    PERMISSIONS.USER_READ,

    PERMISSIONS.STUDENT_READ,
    PERMISSIONS.STUDENT_UPDATE,

    PERMISSIONS.TEACHER_READ,
    PERMISSIONS.TEACHER_UPDATE,

    PERMISSIONS.PARENT_READ,

    PERMISSIONS.DEPARTMENT_READ,

    PERMISSIONS.CLASS_READ,
    PERMISSIONS.CLASS_CREATE,
    PERMISSIONS.CLASS_UPDATE,

    PERMISSIONS.ENROLLMENT_READ,

    PERMISSIONS.ATTENDANCE_READ,
    PERMISSIONS.ATTENDANCE_CREATE,
    PERMISSIONS.ATTENDANCE_UPDATE,

    PERMISSIONS.ASSIGNMENT_READ,
    PERMISSIONS.ASSIGNMENT_CREATE,
    PERMISSIONS.ASSIGNMENT_UPDATE,
    PERMISSIONS.ASSIGNMENT_DELETE,
    PERMISSIONS.ASSIGNMENT_MANAGE,

    PERMISSIONS.SUBMISSION_READ,
    PERMISSIONS.SUBMISSION_CREATE,
    PERMISSIONS.SUBMISSION_UPDATE,
    PERMISSIONS.SUBMISSION_MANAGE,

    PERMISSIONS.TEST_READ,
    PERMISSIONS.TEST_CREATE,
    PERMISSIONS.TEST_UPDATE,

    PERMISSIONS.QUESTION_READ,
    PERMISSIONS.QUESTION_CREATE,
    PERMISSIONS.QUESTION_UPDATE,

    PERMISSIONS.TEST_ATTEMPT_READ,
    PERMISSIONS.TEST_ATTEMPT_CREATE,

    PERMISSIONS.LIVE_SESSION_READ,
    PERMISSIONS.LIVE_SESSION_CREATE,
    PERMISSIONS.LIVE_SESSION_UPDATE,
    PERMISSIONS.LIVE_SESSION_MANAGE,

    PERMISSIONS.STUDY_MATERIAL_READ,
    PERMISSIONS.STUDY_MATERIAL_CREATE,
    PERMISSIONS.STUDY_MATERIAL_UPDATE,
    PERMISSIONS.STUDY_MATERIAL_DELETE,

    PERMISSIONS.NOTIFICATION_READ,
    PERMISSIONS.NOTIFICATION_CREATE,

    PERMISSIONS.GAMIFICATION_READ,
    PERMISSIONS.ACHIEVEMENT_READ,
    PERMISSIONS.USER_ACHIEVEMENT_READ,
    PERMISSIONS.LEADERBOARD_READ,
    PERMISSIONS.STREAK_READ,

    PERMISSIONS.CERTIFICATE_READ,
    PERMISSIONS.CERTIFICATE_CREATE,

    PERMISSIONS.REPORT_READ,
  ],

  [ROLES.SUPPORT]: [
    PERMISSIONS.USER_READ,

    PERMISSIONS.STUDENT_READ,
    PERMISSIONS.EMPLOYEE_READ,
    PERMISSIONS.PARENT_READ,
    PERMISSIONS.CUSTOMER_READ,

    PERMISSIONS.CONVERSATION_READ,
    PERMISSIONS.CONVERSATION_CREATE,
    PERMISSIONS.CONVERSATION_UPDATE,

    PERMISSIONS.MESSAGE_READ,
    PERMISSIONS.MESSAGE_CREATE,
    PERMISSIONS.MESSAGE_UPDATE,

    PERMISSIONS.SUPPORT_READ,
    PERMISSIONS.SUPPORT_CREATE,
    PERMISSIONS.SUPPORT_UPDATE,
    PERMISSIONS.SUPPORT_MANAGE,

    PERMISSIONS.TICKET_READ,
    PERMISSIONS.TICKET_CREATE,
    PERMISSIONS.TICKET_UPDATE,
    PERMISSIONS.TICKET_MANAGE,

    PERMISSIONS.TICKET_MESSAGE_READ,
    PERMISSIONS.TICKET_MESSAGE_CREATE,
    PERMISSIONS.TICKET_MESSAGE_UPDATE,
    PERMISSIONS.TICKET_MESSAGE_MANAGE,

    PERMISSIONS.NOTIFICATION_READ,

    PERMISSIONS.REPORT_READ,
  ],

  [ROLES.EMPLOYEE]: [
    PERMISSIONS.USER_READ,

    PERMISSIONS.EMPLOYEE_READ,
    PERMISSIONS.EMPLOYEE_UPDATE,

    PERMISSIONS.DEPARTMENT_READ,

    PERMISSIONS.ATTENDANCE_READ,
    PERMISSIONS.ATTENDANCE_CREATE,

    PERMISSIONS.LEAVE_READ,
    PERMISSIONS.LEAVE_CREATE,
    PERMISSIONS.LEAVE_UPDATE,

    PERMISSIONS.PAYROLL_READ,

    PERMISSIONS.PERFORMANCE_READ,

    PERMISSIONS.EMPLOYEE_DOCUMENT_READ,

    PERMISSIONS.NOTIFICATION_READ,
    PERMISSIONS.NOTIFICATION_PREFERENCE_READ,
    PERMISSIONS.NOTIFICATION_PREFERENCE_UPDATE,

    PERMISSIONS.GAMIFICATION_READ,
    PERMISSIONS.ACHIEVEMENT_READ,
    PERMISSIONS.USER_ACHIEVEMENT_READ,
    PERMISSIONS.LEADERBOARD_READ,
    PERMISSIONS.STREAK_READ,

    PERMISSIONS.SUPPORT_READ,
    PERMISSIONS.SUPPORT_CREATE,
    PERMISSIONS.SUPPORT_UPDATE,

    PERMISSIONS.CONVERSATION_READ,
    PERMISSIONS.CONVERSATION_CREATE,
    PERMISSIONS.MESSAGE_READ,
    PERMISSIONS.MESSAGE_CREATE,

    PERMISSIONS.DEVICE_READ,
  ],

  [ROLES.PARENT]: [
    PERMISSIONS.USER_READ,

    PERMISSIONS.PARENT_READ,
    PERMISSIONS.PARENT_UPDATE,

    PERMISSIONS.STUDENT_READ,

    PERMISSIONS.ENROLLMENT_READ,

    PERMISSIONS.ATTENDANCE_READ,

    PERMISSIONS.ASSIGNMENT_READ,
    PERMISSIONS.SUBMISSION_READ,

    PERMISSIONS.TEST_READ,
    PERMISSIONS.TEST_ATTEMPT_READ,

    PERMISSIONS.LIVE_SESSION_READ,

    PERMISSIONS.STUDY_MATERIAL_READ,

    PERMISSIONS.NOTIFICATION_READ,
    PERMISSIONS.NOTIFICATION_PREFERENCE_READ,
    PERMISSIONS.NOTIFICATION_PREFERENCE_UPDATE,

    PERMISSIONS.GAMIFICATION_READ,
    PERMISSIONS.ACHIEVEMENT_READ,
    PERMISSIONS.USER_ACHIEVEMENT_READ,
    PERMISSIONS.LEADERBOARD_READ,
    PERMISSIONS.STREAK_READ,

    PERMISSIONS.CERTIFICATE_READ,

    PERMISSIONS.INVOICE_READ,
    PERMISSIONS.PAYMENT_READ,

    PERMISSIONS.CONVERSATION_READ,
    PERMISSIONS.CONVERSATION_CREATE,

    PERMISSIONS.MESSAGE_READ,
    PERMISSIONS.MESSAGE_CREATE,

    PERMISSIONS.SUPPORT_READ,
    PERMISSIONS.SUPPORT_CREATE,
    PERMISSIONS.SUPPORT_UPDATE,

    PERMISSIONS.DEVICE_READ,
  ],

  [ROLES.STUDENT]: [
    PERMISSIONS.USER_READ,

    PERMISSIONS.STUDENT_READ,
    PERMISSIONS.STUDENT_UPDATE,

    PERMISSIONS.CLASS_READ,
    PERMISSIONS.ENROLLMENT_READ,

    PERMISSIONS.ATTENDANCE_READ,

    PERMISSIONS.ASSIGNMENT_READ,
    PERMISSIONS.SUBMISSION_READ,
    PERMISSIONS.SUBMISSION_CREATE,

    PERMISSIONS.TEST_READ,
    PERMISSIONS.TEST_ATTEMPT_READ,
    PERMISSIONS.TEST_ATTEMPT_CREATE,
    PERMISSIONS.TEST_ATTEMPT_UPDATE,

    PERMISSIONS.QUESTION_READ,

    PERMISSIONS.LIVE_SESSION_READ,

    PERMISSIONS.STUDY_MATERIAL_READ,

    PERMISSIONS.NOTIFICATION_READ,
    PERMISSIONS.NOTIFICATION_PREFERENCE_READ,
    PERMISSIONS.NOTIFICATION_PREFERENCE_UPDATE,

    PERMISSIONS.GAMIFICATION_READ,
    PERMISSIONS.ACHIEVEMENT_READ,
    PERMISSIONS.USER_ACHIEVEMENT_READ,
    PERMISSIONS.LEADERBOARD_READ,
    PERMISSIONS.STREAK_READ,

    PERMISSIONS.CERTIFICATE_READ,

    PERMISSIONS.INVOICE_READ,
    PERMISSIONS.PAYMENT_READ,

    PERMISSIONS.CONVERSATION_READ,
    PERMISSIONS.CONVERSATION_CREATE,

    PERMISSIONS.MESSAGE_READ,
    PERMISSIONS.MESSAGE_CREATE,

    PERMISSIONS.SUPPORT_READ,
    PERMISSIONS.SUPPORT_CREATE,
    PERMISSIONS.SUPPORT_UPDATE,

    PERMISSIONS.DEVICE_READ,
  ],
});

const normalizeRole = (role) => {
  if (!role) {
    return null;
  }

  const normalized = String(role)
    .trim()
    .toLowerCase();

  return ROLE_VALUES.includes(normalized)
    ? normalized
    : null;
};

const getRoleHierarchy = (role) => {
  const normalizedRole = normalizeRole(role);

  if (!normalizedRole) {
    return 0;
  }

  return ROLE_HIERARCHY[normalizedRole] || 0;
};

const hasRole = (user, role) => {
  if (!user || !role) {
    return false;
  }

  const requiredRole = normalizeRole(role);

  if (!requiredRole) {
    return false;
  }

  const userRoles = Array.isArray(user.roles)
    ? user.roles
    : [user.role];

  return userRoles
    .filter(Boolean)
    .map(normalizeRole)
    .includes(requiredRole);
};

const hasAnyRole = (user, roles = []) => {
  if (
    !user ||
    !Array.isArray(roles) ||
    roles.length === 0
  ) {
    return false;
  }

  return roles.some((role) =>
    hasRole(user, role)
  );
};

const hasAllRoles = (user, roles = []) => {
  if (
    !user ||
    !Array.isArray(roles) ||
    roles.length === 0
  ) {
    return false;
  }

  return roles.every((role) =>
    hasRole(user, role)
  );
};

const hasMinimumRole = (
  user,
  minimumRole
) => {
  if (!user || !minimumRole) {
    return false;
  }

  const requiredLevel =
    getRoleHierarchy(minimumRole);

  if (requiredLevel === 0) {
    return false;
  }

  const userRoles = Array.isArray(user.roles)
    ? user.roles
    : [user.role];

  return userRoles.some(
    (role) =>
      getRoleHierarchy(role) >=
      requiredLevel
  );
};

const getRolePermissions = (role) => {
  const normalizedRole = normalizeRole(role);

  if (!normalizedRole) {
    return [];
  }

  return [
    ...(rolePermissions[normalizedRole] || []),
  ];
};

const getUserPermissions = (user) => {
  if (!user) {
    return [];
  }

  const roles = Array.isArray(user.roles)
    ? user.roles
    : [user.role];

  const permissions = new Set();

  for (const role of roles) {
    for (const permission of getRolePermissions(
      role
    )) {
      permissions.add(permission);
    }
  }

  if (Array.isArray(user.permissions)) {
    for (const permission of user.permissions) {
      if (ALL_PERMISSIONS.includes(permission)) {
        permissions.add(permission);
      }
    }
  }

  return [...permissions];
};

const hasPermission = (
  user,
  permission,
  explicitPermissions = []
) => {
  if (!user || !permission) {
    return false;
  }

  const normalizedPermission =
    String(permission).trim();

  if (
    !ALL_PERMISSIONS.includes(
      normalizedPermission
    )
  ) {
    return false;
  }

  // Super admin has every permission.
  if (
    hasRole(
      user,
      ROLES.SUPER_ADMIN
    )
  ) {
    return true;
  }

  // Explicit permissions assigned to the user.
  if (
    Array.isArray(
      explicitPermissions
    ) &&
    explicitPermissions.includes(
      normalizedPermission
    )
  ) {
    return true;
  }

  // Permissions inherited from the user's role.
  return getUserPermissions(
    user
  ).includes(
    normalizedPermission
  );
};

const hasAnyPermission = (
  user,
  permissions = [],
  explicitPermissions = []
) => {
  if (
    !user ||
    !Array.isArray(permissions) ||
    permissions.length === 0
  ) {
    return false;
  }

  return permissions.some(
    (permission) =>
      hasPermission(
        user,
        permission,
        explicitPermissions
      )
  );
};

const hasAllPermissions = (
  user,
  permissions = [],
  explicitPermissions = []
) => {
  if (
    !user ||
    !Array.isArray(permissions) ||
    permissions.length === 0
  ) {
    return false;
  }

  return permissions.every(
    (permission) =>
      hasPermission(
        user,
        permission,
        explicitPermissions
      )
  );
};

const canManageRole = (
  actorRole,
  targetRole
) => {
  const actorLevel =
    getRoleHierarchy(actorRole);

  const targetLevel =
    getRoleHierarchy(targetRole);

  if (
    actorLevel === 0 ||
    targetLevel === 0
  ) {
    return false;
  }

  return actorLevel > targetLevel;
};

const canAccessInstitute = (
  user,
  instituteId
) => {
  if (!user) {
    return false;
  }

  if (
    hasRole(
      user,
      ROLES.SUPER_ADMIN
    )
  ) {
    return true;
  }

  if (
    !user.instituteId ||
    !instituteId
  ) {
    return false;
  }

  return (
    String(user.instituteId) ===
    String(instituteId)
  );
};

const getAccessibleRoles = (
  actorRole
) => {
  const actorLevel =
    getRoleHierarchy(actorRole);

  if (actorLevel === 0) {
    return [];
  }

  return ROLE_VALUES.filter(
    (role) =>
      ROLE_HIERARCHY[role] <
      actorLevel
  );
};

export {
  ROLE_HIERARCHY,
  PERMISSIONS,
  ALL_PERMISSIONS,
  rolePermissions,
  normalizeRole,
  getRoleHierarchy,
  hasRole,
  hasAnyRole,
  hasAllRoles,
  hasMinimumRole,
  getRolePermissions,
  getUserPermissions,
  hasPermission,
  hasAnyPermission,
  hasAllPermissions,
  canManageRole,
  canAccessInstitute,
  getAccessibleRoles,
};

export default {
  ROLE_HIERARCHY,
  PERMISSIONS,
  ALL_PERMISSIONS,
  rolePermissions,
  normalizeRole,
  getRoleHierarchy,
  hasRole,
  hasAnyRole,
  hasAllRoles,
  hasMinimumRole,
  getRolePermissions,
  getUserPermissions,
  hasPermission,
  hasAnyPermission,
  hasAllPermissions,
  canManageRole,
  canAccessInstitute,
  getAccessibleRoles,
};
